### ISSUE TITLE
好像影片的内容都是文档，没看到video链接？

### ISSUE THREAD

**Issue by xiaodongliang** [yiskang/forge-workshop-tw-2020#1]

**Comment by yiskang** [comment]
Hi Xiaodong,

我剛發現首頁有些連結好像沒指對地方，我晚一點在全面檢查一遍

基本上，影片都已經上傳到 YouTube，連結放在每個章節的自主練習裡面（Practice.html 或 Practice.md），滑鼠在圖片點一下會跳轉到 YouTube，可能哪個環節沒弄好，我再檢查一下

謝謝！

**Comment by yiskang** [comment]
連結都更新好了，影片的部份也加上了提示～ :)

**Comment by xiaodongliang** [comment]
我知道怎么回事了！因为在大陆的网络里，Youtube的内容没显示，：） 现在都看到了！谢谢！
