### ISSUE TITLE
活动议程 是HTML source （见图示）

### ISSUE THREAD

**Issue by xiaodongliang** [yiskang/forge-workshop-tw-2020#3]
<img width="947" alt="Screen Shot 2020-05-18 at 5 26 46 PM" src="https://user-images.githubusercontent.com/5087461/82196884-d9ce2d00-992c-11ea-8d8f-4ed7e5033995.png">

**Comment by yiskang** [comment]
這個應應該可以忽略，因為在透過 gh-pages 轉譯成 HTML 時有些格式和路徑不是很正確，所以我寫了一小段 CSS 和 JavaScript 去控制他，所以才會有那幾行出現在在 `*.md` 檔案裡頭，在網頁上是看不到的 :)
